apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "2e2da522619cd198a707c37fc024a068e80b17b6"
        buildDate: "20220105171726"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products
          ports:
            - containerPort: 8080
              name: 8080-tcp
